FROM nginx:alpine
RUN apk add nodejs npm
RUN npm install -g npm@latest

WORKDIR /usr/src/app

COPY . .

COPY .env .env

RUN npm ci --silent

RUN npm run build

WORKDIR /var/www/

RUN ln -s /usr/src/app/dist frontend

CMD ["nginx", "-g", "daemon off;"]
