FROM node:slim

WORKDIR /usr/src/app

COPY . .

RUN npm i --silent

CMD ["npm", "run", "dev"]

# FROM nginx:alpine

# RUN apk add nodejs npm

# WORKDIR /var/www/frontend

# COPY . .

# RUN npm install -g npm@latest

# RUN npm ci --silent

# RUN npm run build

# CMD ["nginx", "-g", "daemon off;"]