version: '3.9'
services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro 
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    volumes: 
      - "./frontend/:/usr/src/app/"
    environment:
      - VITE_CONTEXT=DEV
      # - VITE_CONTEXT=MOCKUP
    restart: unless-stopped
    env_file: .env

  # Don't forget to uncomment the following conteneur if you want to have the mockup available :) 

  # backend_mockup:
  #   build:
  #     context: ./backend_mockup
  #     dockerfile: Dockerfile.local
  #   volumes: 
  #     - "./backend_mockup/:/svr/app"
  #   restart: unless-stopped
  #   depends_on:
  #     - database

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    volumes: 
      - "./backend/:/svr/app"
    restart: unless-stopped
    env_file: .env
    depends_on:
      - database

  database:
    image: bitnami/postgresql:14
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=dev
      - POSTGRESQL_PASSWORD=local
      - POSTGRESQL_DATABASE=db
      - POSTGRESQL_POSTGRES_PASSWORD=localroot
      - POSTGRESQL_MASTER_PORT=5432
    volumes:
      - db:/bitnami/postgresql
    
  admin:
    image: bitnami/phppgadmin
    restart: unless-stopped
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT_NUMBER=5432
    volumes:
      - db:/bitnami/postgresql
    ports: 
      - 5431:8080

    depends_on:
      - database
    
volumes:
  db:
