export const jwtConstants = {
  JWT_ACCESS_TOKEN_SECRET: 'VeryComplicatePassword',
  //   JWT_ACCESS_TOKEN_EXPIRATION_TIME: 15,
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: 9000,
  JWT_REFRESH_TOKEN_SECRET: 'VeryComplicatePassword',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: 86400, // 1 week
};
